# Generated by Django 4.1.7 on 2023-05-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarea',
            new_name='Tareas',
        ),
    ]
