# Generated by Django 4.1.7 on 2023-05-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_rename_tarea_tareas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
